#配置日志
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/mac/Documents/workspace/graduation/log/sell.log
#  level:
#    com.su.logger.LoggerTest: debug


#配置数据库设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 设置数据库连接url，并指定字符集为uft-8，并且忽略ssl连接模式
    url: jdbc:mysql://172.18.114.90:3306/graduation?characterEncoding=utf-8&useSSL=false
  jpa:
    # 控制台打印出SQL语句，方便调试
    show-sql: true
  #全局的配置：当对象属性值为null时，不将其序列化到json数据中
  #jackson:
   # default-property-inclusion: non_null
server:
  servlet:
    # 临时去掉路径名，用于微信验证域名
    context-path: /sell

wechat:
  mpAppId: wxe227becfe60132e2
  mpAppSecret: 534253ebd7cdae3711f401a3c4b13ecb
